env:
  commonjs: false
  browser: true
  es2021: true
  jquery: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
rules:
  no-var: off
  guard-for-in: off
  no-trailing-spaces: off
  camelcase: off
  padded-blocks: off
  prefer-const: off
  max-len: off
  indent:
    - error
    - 4
