# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
 - name: Setup django
   init: |
      export INVENTREE_DB_ENGINE='sqlite3'
      export  INVENTREE_DB_NAME='/workspace/InvenTree/dev/database.sqlite3'
      export  INVENTREE_MEDIA_ROOT='/workspace/InvenTree/dev/media'
      export INVENTREE_STATIC_ROOT='/workspace/InvenTree/dev/static'
      export PIP_USER='no'

      python3 -m venv venv
      source venv/bin/activate
      pip install invoke
      inv install
      mkdir dev
      inv update
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'test@test.com', 'inventree')" | python InvenTree/manage.py shell
   env:
      INVENTREE_DB_ENGINE: 'sqlite3'
      INVENTREE_DB_NAME: '/workspace/data/database.sqlite3'
      INVENTREE_MEDIA_ROOT: '/workspace/data/media'
      INVENTREE_STATIC_ROOT: '/workspace/data/static'
      PIP_USER: 'no'

 - name: Start server
   command: |
      inv server
   env:
      INVENTREE_DB_ENGINE: 'sqlite3'
      INVENTREE_DB_NAME: '/workspace/data/database.sqlite3'
      INVENTREE_MEDIA_ROOT: '/workspace/data/media'
      INVENTREE_STATIC_ROOT: '/workspace/data/static'
      PIP_USER: 'no'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
