dist: xenial

language: python
python:
    - 3.5

addons:
    apt-packages:
        -sqlite3

before_install:
    - make setup
    - make setup_ci

script:
    - make coverage
    - make style

after_success:
    - coveralls