language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

before_install:
    - pip install pep8
    
script:
    # TODO - Only perform PEP8 checks on files that have been changed in this push / PR
    - find . -name \*.py -exec pep8 --ignore=E402 {} +