dist: xenial

language: python
python:
    - 3.6
    - 3.7

addons:
    apt-packages:
        -sqlite3

before_install:
    - make requirements
    - make setup
    - make migrate

script:
    - git ls-files --exclude-standard --others
    - make coverage
    - make style

after_success:
    - coveralls