dist: xenial

language: python
python:
    - 3.5

addons:
    apt-packages:
        -sqlite3

before_install:
    - make install
    - make migrate

script:
    - make coverage
    - make style
    - git ls-files --exclude-standard --others

after_success:
    - coveralls