version: "3.8"

# Docker compose recipe for InvenTree
# - Runs PostgreSQL as the database backend
# - Serves web data using Gunicorn
# - Runs the background worker process
# - Runs nginx as a reverse proxy

services:
    # Database service
    # Use PostgreSQL as the database backend
    # Note: this can be changed to a different backend,
    #       just make sure that you change the INVENTREE_DB_xxx vars below
    db:
        image: postgres
        container_name: inventree_db
        ports:
            - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpassword
        volumes:
            - data:/var/lib/postgresql/data/
        restart: unless-stopped

    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree:
        build:
            context: .
            args:
                repository: "https://github.com/SchrodingersGat/InvenTree.git"
                branch: "django-q"
        image: inventree/inventree:latest
        container_name: inventree_server
        ports:
            - "8080:8080"
        depends_on:
            - db
        volumes:
            - data:/home/inventree/data
        environment:
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_PORT=5432
            - INVENTREE_DB_HOST=db
        restart: unless-stopped

    worker:
        build:
            context: .
            args:
                repository: "https://github.com/SchrodingersGat/InvenTree.git"
                branch: "django-q"
        entrypoint: ./start_worker.sh
        image: inventree/worker:latest
        container_name: inventree_worker
        depends_on:
            - db
            - inventree
        volumes:
            - data:/home/inventree/data
        environment:
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_PORT=5432
            - INVENTREE_DB_HOST=db
        restart: unless-stopped

volumes:
    data:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            device: c:/abcdef