# Perform CI checks, and calculate code coverage

name: SQLite

on: ["push", "pull_request"]

jobs:

  # Run tests on SQLite database
  # These tests are used for code coverage analysis
  coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_NAME: './test_db.sqlite'
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get update
          pip3 install invoke
          invoke install
      - name: Coverage Tests
        run: |
          invoke coverage
      - name: Data Import Export
        run: |
          rm test_db.sqlite
          invoke migrate
          invoke import-fixtures
          invoke export-records -f data.json
          rm test_db.sqlite
          invoke migrate
          invoke import-records -f data.json
      - name: Upload Coverage Report
        run: coveralls
