# Build and push latest docker image on push to master branch

name: Docker Build

on:
  push:
    branches:
      - 'master'

jobs:
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          repository: inventree/inventree
          tags: inventree/inventree:latest
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
