# Test that the docker file builds correctly

name: Docker

on: ["push", "pull_request"]

jobs:
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: cd docker && docker build . --tag inventree:$(date +%s)
    