# Checks for each PR

name: PR checks

on:
  pull_request:
    branches-ignore:
      - l10*

jobs:

  check_version:
    name: check version number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check version number
        run: |
          python3 ci/check_version_number.py --branch ${{ github.base_ref }}
